# Generated by Django 6.0.6 on 2026-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_ts_ms', models.BigIntegerField(help_text='Tiempo en ms desde el boot del Pico W')),
                ('temp_internal', models.FloatField(help_text='Temperatura interna del RP2040 en grados Celsius')),
                ('pwm_duty', models.PositiveSmallIntegerField(help_text='Duty cycle PWM 0-255')),
                ('reg0', models.IntegerField(default=0)),
                ('reg1', models.IntegerField(default=0)),
                ('reg2', models.IntegerField(default=0)),
                ('reg3', models.IntegerField(default=0)),
                ('reg4', models.IntegerField(default=0)),
                ('reg5', models.IntegerField(default=0)),
                ('reg6', models.IntegerField(default=0)),
                ('reg7', models.IntegerField(default=0)),
                ('modbus_errors', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registro de telemetria',
                'verbose_name_plural': 'Registros de telemetria',
                'ordering': ['-received_at'],
            },
        ),
    ]
